#!/bin/sh

set -e

tar xzf tcl8*gz
tar xzf tk8*gz
tar xzf tki*gz

export CFLAGS="$CFLAGS -DSQLITE_USE_URI=1"

# fix PATH: Tk's configure needs /usr/bin/pkg-config, not the one under $SAGE_LOCAL/bin
export PATH="/usr/bin:$PATH"

echo "Compiling Tcl"
(cd tcl8*/unix 
    ./configure --prefix=$SAGE_LOCAL --libdir=$SAGE_LOCAL/lib --enable-threads 
    make
    make install
    )

echo "Compiling Tk"
(cd tk8*/unix 
    ./configure --with-tcl=$SAGE_LOCAL/lib --libdir=$SAGE_LOCAL/lib --enable-aqua
    make
    make install
    )

echo "Compiling Tkinter"
(cd tkinter-1.0
    rm -rf build || true
    $SAGE_LOCAL/bin/python3 setup.py install
    )

echo "Compiling Steenrod Tcl library"
tar xzf Steenrod*tar.gz
(cd steenrod*
    ./configure --with-tcl=$SAGE_LOCAL/lib  --libdir=$SAGE_LOCAL/lib
    make
    make install
    )

#echo "Installing BWidget-1.8.0"
#cp -rf BWidget-1.8.0 $SAGE_LOCAL/lib 
echo "Installing BWidget"
tar xzf bwidget* -C $SAGE_LOCAL/lib

echo "Installing pdf4tcl"
tar xzf pdf4tcl* -C $SAGE_LOCAL/lib

echo "Done"

