#!/bin/sh

set -e

TCLLIB=$SAGE_LOCAL/tcl

echo "Compiling Steenrod Tcl library"
tar xzf Steenrod*tar.gz
(cd steenrod*
    ./configure --prefix=$SAGE_LOCAL/lib/tcl
    make
    sudo make install
    )

sudo mkdir -p $TCLLIB/lib
cp -ar /usr/lib/Steenrod* $TCLLIB/lib

echo "Installing BWidget"
sudo tar xzf bwidget* -C $TCLLIB/lib

echo "Installing pdf4tcl"
sudo tar xzf pdf4tcl* -C $TCLLIB/lib

echo "Done"

