#!/bin/sh

set -e

echo "Compiling Steenrod Tcl library"
tar xzf Steenrod*tar.gz
(cd steenrod*
    ./configure
    make
    sudo make install
    )

#echo "Installing BWidget-1.8.0"
#cp -rf BWidget-1.8.0 $SAGE_LOCAL/lib 

TCLLIB=$(echo "puts [info lib]" | tclsh) 

echo "Installing BWidget"
sudo tar xzf bwidget* -C $TCLLIB

echo "Installing pdf4tcl"
sudo tar xzf pdf4tcl* -C $TCLLIB

echo "Done"

